// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockedHeartbeatEnabler is an autogenerated mock type for the MockedHeartbeatEnabler type
type MockedHeartbeatEnabler struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *MockedHeartbeatEnabler) Start() {
	_m.Called()
}
