// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	shard "github.com/multivactech/MultiVAC/model/shard"
	mock "github.com/stretchr/testify/mock"

	wire "github.com/multivactech/MultiVAC/model/wire"
)

// MockedReshardHandler is an autogenerated mock type for the MockedReshardHandler type
type MockedReshardHandler struct {
	mock.Mock
}

// GetEnableShards provides a mock function with given fields:
func (_m *MockedReshardHandler) GetEnableShards() []shard.Index {
	ret := _m.Called()

	var r0 []shard.Index
	if rf, ok := ret.Get(0).(func() []shard.Index); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]shard.Index)
		}
	}

	return r0
}

// HandleConfirmationMessage provides a mock function with given fields: msg
func (_m *MockedReshardHandler) HandleConfirmationMessage(msg *wire.MsgBlockConfirmation) {
	_m.Called(msg)
}

// StartEnabledShardControllers provides a mock function with given fields:
func (_m *MockedReshardHandler) StartEnabledShardControllers() {
	_m.Called()
}
