// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	icontroller "github.com/multivactech/MultiVAC/interface/icontroller"
	mock "github.com/stretchr/testify/mock"

	shard "github.com/multivactech/MultiVAC/model/shard"
)

// MockedShardRouter is an autogenerated mock type for the MockedShardRouter type
type MockedShardRouter struct {
	mock.Mock
}

// GetAllShardControllers provides a mock function with given fields:
func (_m *MockedShardRouter) GetAllShardControllers() []icontroller.IShardController {
	ret := _m.Called()

	var r0 []icontroller.IShardController
	if rf, ok := ret.Get(0).(func() []icontroller.IShardController); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]icontroller.IShardController)
		}
	}

	return r0
}

// GetShardController provides a mock function with given fields: shardIndex
func (_m *MockedShardRouter) GetShardController(shardIndex shard.Index) icontroller.IShardController {
	ret := _m.Called(shardIndex)

	var r0 icontroller.IShardController
	if rf, ok := ret.Get(0).(func(shard.Index) icontroller.IShardController); ok {
		r0 = rf(shardIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(icontroller.IShardController)
		}
	}

	return r0
}
