// Code generated by mockery v1.0.0. DO NOT EDIT.

package rpcserver

import (
	message "github.com/multivactech/MultiVAC/processor/shared/message"
	mock "github.com/stretchr/testify/mock"
)

// rpcHandler is an autogenerated mock type for the rpcHandler type
type MockRpcHandler struct {
	mock.Mock
}

// HandleRPCReq provides a mock function with given fields: req
func (_m *MockRpcHandler) HandleRPCReq(req *message.RPCReq) *message.RPCResp {
	ret := _m.Called(req)

	var r0 *message.RPCResp
	if rf, ok := ret.Get(0).(func(*message.RPCReq) *message.RPCResp); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*message.RPCResp)
		}
	}

	return r0
}
