// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package sync

import (
	"github.com/multivactech/MultiVAC/configs/config"
	"github.com/multivactech/MultiVAC/interface/isync"
	"github.com/multivactech/MultiVAC/model/shard"
	"github.com/multivactech/MultiVAC/processor/shared/message"
)

// Injectors from injector.go:

func ProvideStorageSyncManager(shard2 shard.Index, sn storageSyncContract, pubSubMgr *message.PubSubManager) isync.SyncManager {
	syncStorageWorker := newStorageWorker(shard2, sn)
	syncSyncManager := provideSyncManager(shard2, syncStorageWorker, pubSubMgr)
	return syncSyncManager
}

func ProvideMinerSyncManager(shard2 shard.Index, miner minerSyncContract, pubSubMgr *message.PubSubManager) isync.SyncManager {
	syncMinerWorker := newMinerWorker(shard2, miner)
	syncSyncManager := provideSyncManager(shard2, syncMinerWorker, pubSubMgr)
	return syncSyncManager
}

// injector.go:

// NewSyncManager creates a new SyncManager instance.
// shard is the given shard for this SyncManager to work on.
// sn is the StorageNode instance in this shard for storage node, nil for miner node.
// abc is the AppBlockChain instance in this shard for miner node, nil for storage node.
func NewSyncManager(shard2 shard.Index, sn storageSyncContract, miner minerSyncContract, pubSubMgr *message.PubSubManager) isync.SyncManager {
	if config.GetNodeType() == config.StorageNode {
		return ProvideStorageSyncManager(shard2, sn, pubSubMgr)
	}
	return ProvideMinerSyncManager(shard2, miner, pubSubMgr)
}

func provideSyncManager(shard2 shard.Index, worker syncWorker, pubSubMgr *message.PubSubManager) *syncManager {
	mgr := &syncManager{
		shard:    shard2,
		state:    newSyncState(pubSubMgr),
		worker:   worker,
		actorCtx: message.NewActorContext(),
	}
	worker.setManager(mgr)
	return mgr
}

func provideManager(idx shard.Index, pubSubMgr *message.PubSubManager) *syncManager {
	return &syncManager{
		shard:    idx,
		state:    newSyncState(pubSubMgr),
		actorCtx: message.NewActorContext(),
	}
}
